#!/bin/bash
let z=1
let clearancelvl=2
read response
case "$response" in
"setlevel")
echo "  $(tput setaf 1)user: $(tput setaf 0)"
read clearanceuser
case $clearanceuser in	
	"jbrown")
	echo "id: "
	read clearanceid
	case "$clearanceid" in
		"255")
		echo "level: "
		read "$clearancelevel"
		case $clearancelevel in
			"3")
			echo "Clearance Level of jbrown set to 3! "
			break
			;;
			*)
			echo "invalid level! "
			;;
			esac
		;;
		*)
		echo "invalid id! "
		;;
		esac
	;;
;;
esac
